### ISSUE TITLE
Running "fix" on an empty module fails

### ISSUE THREAD

**Issue by lihaoyi** [joan38/mill-scalafix#213]
Sister ticket to https://github.com/com-lihaoyi/mill/issues/4006

> A project with _just_ this `build.mill` (using Mill `0.12.2`) dies on `./mill __.fix`.
> 
> ```
> package build
> 
> import $ivy.`com.goyeau::mill-scalafix::0.4.2`
> import com.goyeau.mill.scalafix.ScalafixModule
> import mill.scalalib.SbtModule
> 
> object main extends SbtModule with ScalafixModule {
>     def scalaVersion = "2.13.15"
> }
> ```
> 
> It might seem strange not to have any sources in a module but I have a couple of "aggregation" modules that simply list other modules that they depend on. This used to work fine (pre `0.12`).
> 
> Adding a single source file makes the problem go away ... but then I have a useless source file. :-)

**Comment by lihaoyi** [comment]
CC @joan38 , not sure how easy this is to fix but it seems like it shouldn't be too hard

**Comment by joan38** [comment]
After running a reproducing test, it sounds like it's an issue with the `ScalaModule.semanticDbData` task:
```
[171] project.semanticDbData java.nio.file.NoSuchFileException: /Users/jgoyeau/IdeaProjects/mill-scalafix/out/mill-scalafix/0.12.0/test/test.dest/sandbox/run-1/out/project/semanticDbData.dest/classes
[171]     os.walk$stream$.attrs(ListOps.scala:205)
[171]     os.walk$stream$.apply(ListOps.scala:166)
[171]     os.walk$.apply(ListOps.scala:96)
[171]     mill.scalalib.SemanticDbJavaModule$.copySemanticdbFiles(SemanticDbJavaModule.scala:227)
[171]     mill.scalalib.ScalaModule.$anonfun$semanticDbData$6(ScalaModule.scala:653)
[171]     mill.api.Result$Success.map(Result.scala:38)
[171]     mill.api.Result$Success.map(Result.scala:37)
[171]     mill.scalalib.ScalaModule.$anonfun$semanticDbData$2(ScalaModule.scala:649)
[171]     mill.define.Task$TraverseCtx.evaluate(Task.scala:215)
[171]     at munit.FunSuite.assert(FunSuite.scala:11)
[171]     at com.goyeau.mill.scalafix.FixIntegrationTests.$anonfun$new$29(FixIntegrationTests.scala:91)
```

We could wrap a try around the call but I think this should be fixed in mill itself.

**Comment by joan38** [comment]
@lihaoyi https://github.com/com-lihaoyi/mill/pull/4249 should fix this issue

**Comment by joan38** [comment]
This should be fixed in the next release of Mill (`0.12.6`)

**Comment by lihaoyi** [comment]
Thanks joan!
